version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db-container
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: symfony_db
    restart: on-failure

  adminer:
    image: adminer:latest
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - php
    ports:
      - "8000:80"
    restart: on-failure
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    restart: on-failure
    volumes:
      - ./app:/var/www/app
