version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: db-container
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_db
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - php
    ports:
    - "8000:80"
    restart: on-failure
    volumes:
    - ./app:/var/www/app
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    ports:
    - "9000:9000"
    restart: on-failure
    volumes:
    - ./app:/var/www/app
